### ISSUE TITLE
Unix Sockets

### ISSUE THREAD

**Issue by darkalchemy** [1ma/RedisSessionHandler#13]
Can you add the option to use this when redis uses unix sockets, instead of ip:port?

**Comment by 1ma** [comment]
Alright I see the problem, the `parse_url` function in the [SavePathParser](https://github.com/1ma/RedisSessionHandler/blob/master/src/SavePathParser.php#L52) does not seem to like socket urls.

```
[1] boris> parse_url('tcp://1.2.3.4:5678?auth=secret&database=3');
// array(
//   'scheme' => 'tcp',
//   'host' => '1.2.3.4',
//   'port' => 5678,
//   'query' => 'auth=secret&database=3'
// )
[2] boris> parse_url('unix:///var/run/redis/redis.sock?persistent=1&weight=1&database=0');
// false
```

I'll think of a fix, should be easy.

**Comment by darkalchemy** [comment]
Thank you. It's much appreciated.

**Comment by 1ma** [comment]
Please try version 0.9.7 which I just released. In my tests it worked either with or without the `unix://` prefix.

**Comment by darkalchemy** [comment]
Works like a charm!

Thank you
