### ISSUE TITLE
Errors while connecting to redis

### ISSUE THREAD

**Issue by macktab** [1ma/RedisSessionHandler#8]
Get such errors while testing (not always, but very often):
Warning: Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /mnt/www/example.com/includes/RedisSessionHandler/uma/redis-session-handler/src/RedisSessionHandler.php on line 105

Warning: Redis::connect(): connect() failed: php_network_getaddresses: getaddrinfo failed: Name or service not known in /mnt/www/example.com/includes/RedisSessionHandler/uma/redis-session-handler/src/RedisSessionHandler.php on line 105

Fatal error: Uncaught exception 'RedisException' with message 'Redis server went away' in /mnt/www/example.com/includes/RedisSessionHandler/uma/redis-session-handler/src/RedisSessionHandler.php:242 Stack trace: #0 /mnt/www/example.com/includes/RedisSessionHandler/uma/redis-session-handler/src/RedisSessionHandler.php(242): Redis->exists('aninlrkd8dijko6...') #1 /mnt/www/example.com/includes/RedisSessionHandler/uma/redis-session-handler/src/RedisSessionHandler.php(139): UMA\RedisSessionHandler->mustRegenerate('aninlrkd8dijko6...') #2 [internal function]: UMA\RedisSessionHandler->read('aninlrkd8dijko6...') #3 /mnt/www/example.com/1askjdha.php(18): session_start() #4 {main} thrown in /mnt/www/example.com/includes/RedisSessionHandler/uma/redis-session-handler/src/RedisSessionHandler.php on line 242

Fatal error: Uncaught exception 'RedisException' with message 'Redis server went away' in /mnt/www/example.com/includes/RedisSessionHandler/uma/redis-session-handler/src/RedisSessionHandler.php:159 Stack trace: #0 /mnt/www/example.com/includes/RedisSessionHandler/uma/redis-session-handler/src/RedisSessionHandler.php(159): Redis->setex('aninlrkd8dijko6...', 1440, '') #1 [internal function]: UMA\RedisSessionHandler->write('aninlrkd8dijko6...', '') #2 [internal function]: session_write_close() #3 {main} thrown in /mnt/www/example.com/includes/RedisSessionHandler/uma/redis-session-handler/src/RedisSessionHandler.php on line 159

**Comment by 1ma** [comment]
Hmm, all these LoCs have phpredis commands (e.g. `connect()`, `setex()`, `exists()`). Looks like PHP cannot reach the Redis service from time to time.

May I see how you set up your `session.save_path`?

**Comment by macktab** [comment]
session.save_path = "tcp://cache.example.com:6379"

**Comment by 1ma** [comment]
Ok! Do you see the same errors if you use the raw IP instead of a domain name? Just to discard that the problem has nothing to do with DNS resolution.

**Comment by macktab** [comment]
Well, but I get such errors not always, just from time to time.

**Comment by 1ma** [comment]
I understand, but do you still see such intermittent errors if you connect with the server's IP instead of the url?

**Comment by macktab** [comment]
Replaced to session.save_path = "tcp://172.16.1.1:6379" on all app servers, same error.

**Comment by 1ma** [comment]
That's weird because the `php_network_getaddresses` and `getaddrinfo` functions are used to translate URLs to its IP, and now there's none. Are you getting exactly the same error messages? (btw might be worth noting that you have to restart apache or the php-fpm daemon after editing php.ini for the changes to take effect).

**Comment by macktab** [comment]
Sorry, you are right, restarted only on one server. Yes, seems now error is gone.

**Comment by macktab** [comment]
But it is always resolving ok, strange error.

**Comment by 1ma** [comment]
No worries, glad to help. Cheers.

**Comment by macktab** [comment]
But we have redis cluster, so we really need to use dns, because ip can just change.

**Comment by 1ma** [comment]
Ah, then that's the problem. When the DNS query returns a different IP (from another redis daemon in the same cluster) the connection fails because it was opened against another server.

I'm afraid this session handler only supports a simple setup (one redis server). On the bright side Marius Meißner and Michael Grunder have been working on bringing session locking to phpredis, so the native extension might have it soon (see https://github.com/phpredis/phpredis/issues/1267).

**Comment by macktab** [comment]
No , it is not like it is changing ip very often, but it can change, so I can not hardcode ip of redis. But huge thanks for help and link.
