### ISSUE TITLE
Breaking change in phpredis 4.0

### ISSUE THREAD

**Issue by ud-klee** [1ma/RedisSessionHandler#9]
According to https://github.com/phpredis/phpredis/issues/1323 Redis::exists() is now returning integer instead of bool, which breaks

https://github.com/1ma/RedisSessionHandler/blob/061dce59eeadfdc4b15cf29f1e83026196fcc9df/src/RedisSessionHandler.php#L253

Any plans of supporting the newer extension? And perhaps add this info to the known caveats section.

Thanks.

**Comment by 1ma** [comment]
Thank you for the heads up. I'll see if I can support both 3.x and 4.x seamlessly.

**Comment by 1ma** [comment]
In the end that was easy enough, it only involved a boolean casting. I just released version 0.9.6 of the handler, which contains this fix.

Cheers.
